# Level 7: NumPy Arrays for Bioinformatics

`NumPy` is a Python library for numerical data.

SciPy uses NumPy arrays, so this notebook gives basic practice before using SciPy.

In [1]:
import numpy as np

## 1. Create an array

In [2]:
expression = np.array([120, 135, 98, 150, 170])
expression

array([120, 135,  98, 150, 170])

## 2. Calculate summary statistics

In [3]:
expression.mean()

134.6

In [4]:
expression.min(), expression.max()

(98, 170)

## 3. Apply calculations to every value

NumPy can apply one calculation to the whole array.

In [5]:
expression_plus_10 = expression + 10
expression_plus_10

array([130, 145, 108, 160, 180])

## 4. Boolean filtering

In [6]:
high_expression = expression[expression > 130]
high_expression

array([135, 150, 170])

## 5. A two-dimensional array

Rows can represent genes and columns can represent samples.

In [7]:
expression_matrix = np.array([
    [120, 135, 98],
    [45, 50, 42],
    [200, 180, 210]
])

expression_matrix

array([[120, 135,  98],
       [ 45,  50,  42],
       [200, 180, 210]])

In [8]:
row_means = expression_matrix.mean(axis=1)
row_means

array([117.66666667,  45.66666667, 196.66666667])

## Practice tasks

1. Create a NumPy array from `[10, 20, 30, 40, 50]`.
2. Calculate the mean and standard deviation.
3. Select only values greater than 25.
4. Multiply every value by 2.
5. Create a 2D array with 2 genes and 3 samples, then calculate the mean for each gene.

In [ ]:
# Write your answers here
